---
title: Those Boards
timezone: UTC
collections:
  articles:
    title: Articles
    output: true
  boards:
    title: Boards
    output: true
  modules:
    title: Modules
    output: true
  originals:
    title: Originals
    output: true
  posts:
    title: Posts
    output: true
  retired:
    title: Retired
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
